Add switch for modular implicits variant with let operator syntax
modular-implicits/modular-implicits-opam pull request #7
Opened 2023-08-23 09:35 UTC by pxeger

It works, the tests pass, and it bootstraps itself.

2023-08-23 10:29 UTC, pxeger commented
Actually, the two features don't interact properly together yet.

```ocaml
val (let/) : {M : Imp.Control.Monad} -> 'a M.t -> ('a -> 'b M.t) -> 'b M.t

let/ x = Some 2 in return x
```

```
Error: The operator let/ has type
         {M : Imp.Control.Monad} -> 'a M.t -> ('a -> 'b M.t) -> 'b M.t
       but it was expected to have type 'c -> ('d -> 'e) -> 'f
```

2023-08-26 10:44 UTC, yallop reviewed
The "version number" part (`let_syntax`) in the `base-implicits.let_syntax` package suggests that the package is related to the let syntax, but the package metadata itself seems more general.

(It's likely to be tricky to maintain the invariant across all the implicits-compilers, though, since the other packages are part of the main opam repository.)

2023-09-11 14:11 UTC, pxeger commented
Should we just merge this, knowing that it's merely an MVP implementation?

2023-09-11 15:19 UTC, yallop requested changes
Could you also please add [CI configuration](https://github.com/modular-implicits/modular-implicits-opam/tree/master/.github/workflows) (including a badge in the README) for the new switch?

2023-09-11 15:19 UTC, yallop commented on packages/base-implicits/base-implicits.let_syntax/opam
> +authors: ["Jeremy Yallop"]
```suggestion
authors: ["Patrick Reader"]
```

2023-09-13 08:05 UTC, pxeger commented
Before merging I will need to change https://github.com/modular-implicits/modular-implicits-opam/pull/7/files#diff-c4d4a4472caf54b259ef50bf892777a16a577791095ed7dc10a740fab65e2060R28 to `#master`, to break the catch-22, as discussed

2023-09-14 14:23 UTC, pxeger commented
Looks like `[skip CI]` didn't work. I will need admin permissions to merge this because of the catch-22. Or you can just do it.

2023-09-14 14:28 UTC, merged